# /gerenciador-empregos-api/Dockerfile
FROM php:8.3-fpm-alpine

# Instala dependências básicas e extensões PHP para o Laravel
RUN apk add --no-cache \
    build-base libzip-dev zip curl git nodejs npm \
    && docker-php-ext-install pdo pdo_sqlite zip pcntl

# Instala o Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Define o diretório de trabalho padrão dentro do container
WORKDIR /app